### ISSUE TITLE
Nix Haskell tutorial: part I

### ISSUE THREAD

**Issue by srid** [nixos-asia/website#16]
Consolidate the two:

- https://nixos.asia/en/blog/nixify-haskell-project-intro
- https://community.flake.parts/haskell-flake/nixpkgs-haskell

And start a tutorial series on using Nix for Haskell (all the way up to haskell-flake)

**Comment by srid** [comment]
https://nixos.asia/en/nixify-haskell-nixpkgs

**Comment by srid** [comment]
> https://nixos.asia/en/nixify-haskell-nixpkgs

@shivaraj-bh Could you give this is a read and make sure that the software it points to (in github repo) is all good, and in sync with what the post talks about? 

Next step would be: https://github.com/juspay/todo-app/pull/9

**Comment by shivaraj-bh** [comment]
Looks good!
