### ISSUE TITLE
nixos-install-oneclick not working?

### ISSUE THREAD

**Issue by Jatsekku** [nixos-asia/website#37]
Hi,
I'm trying to setup my system in similar manner as you did here: https://nixos.asia/en/nixos-install-oneclick
I tried to run your flake under VM, but partitions are not mounted properly:

```
NAME   FSTYPE   MOUNTPOINT
loop0  squashfs /nix/.ro-store
sr0    iso9660  /iso
vda             
├─vda1 vfat     
├─vda2          
└─vda3 ext4     
```

**Comment by srid** [comment]
Are you using the same flake, `"github:nixos-asia/website?dir=global/nixos-install-oneclick#oneclick"`, including its disko config?

I do not have issues using it on my Parallels VM on macOS:

```
❯ lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda      8:0    0   64G  0 disk 
├─sda1   8:1    0  512M  0 part /boot
├─sda2   8:2    0    1M  0 part 
└─sda3   8:3    0 63.5G  0 part /nix/store
                                /
sr0     11:0    1  2.4G  0 rom  
```

**Comment by Jatsekku** [comment]
Hmm, to be sure I just executed the exact copy from: https://nixos.asia/en/nixos-install-oneclick. 
Disk is the only change /dev/sda -> /dev/vda
```
sudo nix \
    --extra-experimental-features 'flakes nix-command' \
    run github:nix-community/disko#disko-install -- \
    --flake "github:nixos-asia/website?dir=global/nixos-install-oneclick#oneclick" \
    --write-efi-boot-entries \
    --disk main /dev/vda
```
and it's still not mounted:
```
> lsblk -a
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0    7:0    0 923.7M  1 loop /nix/.ro-store
loop1    7:1    0     0B  0 loop 
loop2    7:2    0     0B  0 loop 
loop3    7:3    0     0B  0 loop 
loop4    7:4    0     0B  0 loop 
loop5    7:5    0     0B  0 loop 
loop6    7:6    0     0B  0 loop 
loop7    7:7    0     0B  0 loop 
sr0     11:0    1   970M  0 rom  /iso
vda    253:0    0    50G  0 disk 
├─vda1 253:1    0   500M  0 part 
├─vda2 253:2    0     1M  0 part 
└─vda3 253:3    0  49.5G  0 part 
```

**Comment by srid** [comment]
Since the tutorial delegates the install to the `github:nix-community/disko#disko-install` flake app, you might want to ask in https://github.com/nix-community/disko ?

**Comment by srid** [comment]
FTR, `lsblk` right after the install:

<img width="390" alt="image" src="https://github.com/nixos-asia/website/assets/3998/ccc80fa8-bf57-4729-95d8-9cd88cb2c827">

**Comment by Jatsekku** [comment]
Thanks for support, it turned out that disko was unable to mount partitions due to selected emulation. 
After switching to SATA it worked.
